# Generated by Django 4.2 on 2023-04-15 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='image_upload')),
                ('description', models.TextField(max_length=1000)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_keywords', models.CharField(max_length=60)),
                ('meta_description', models.TextField(max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('product_image', models.ImageField(upload_to='image_upload')),
                ('small_description', models.CharField(max_length=60)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=1000)),
                ('original_price', models.IntegerField(default=1)),
                ('selling_price', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('trending', models.BooleanField(default=True)),
                ('tag', models.CharField(max_length=60)),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_keywords', models.CharField(max_length=60)),
                ('meta_description', models.TextField(max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
    ]
